### ISSUE TITLE
REST-Service API-Layer java.sql.Time doesn't show in UI any value.

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#101]
REST-Service API-Layer java.sql.Time doesn't show in UI any value.

Just create instance, call fillSampleData and save it into MS.

Class:
```
    public static class CalendarData  {

        Timestamp sqlTimestamp;
        Time sqlTime;
        java.sql.Date date;

        public void fillSampleData() {
            sqlTimestamp = new Timestamp(System.currentTimeMillis());
            sqlTime = new Time(System.currentTimeMillis());
            date = new Date(System.currentTimeMillis());
        }
    }

```
![image](https://user-images.githubusercontent.com/17253582/78033932-5c902e00-7367-11ea-8c2e-255db1c3bc2e.png)

**Comment by fh-ms** [comment]
It does, what branch and module versions do you use?

![image](https://user-images.githubusercontent.com/53050506/78043738-04135d80-7374-11ea-8a7d-87667841afc0.png)

**Comment by zdenek-jonas** [comment]
feature/priv224_REST-Service_UI-Layer

**Comment by zdenek-jonas** [comment]
Ok, update alles again, build alles again, works. 
I have really no idea, what was wrong.
