### ISSUE TITLE
REST-Adapter Type Discrepancies

### ISSUE THREAD

**Issue by fh-ms** [microstream-one/microstream#102]
java.lang.Integer objects are returned differently, depending if they are constants or not. Constants are usually -128 to 127. 
![image](https://user-images.githubusercontent.com/53050506/78139654-231ff700-7429-11ea-8bbb-45baadb99767.png)

OptionalInteger/Long/Double and StringBuffer return just one field:
![image](https://user-images.githubusercontent.com/53050506/78140094-c07b2b00-7429-11ea-9073-5881f9048997.png)

**Comment by fh-ms** [comment]
Details microstream-one/microstream-public#97 microstream-one/microstream-public#98

**Comment by zdenek-jonas** [comment]
OK
