### ISSUE TITLE
Layered Entity Concept - Not able to store an entity

### ISSUE THREAD

**Issue by ZorgCK** [microstream-one/microstream#103]
I created a small test project to evaluate the layered entity concept. I added a new entity to a collection in the root. I stored this collection. After restarting the project the collection ist empty again. See following code.

`final Person create  = PersonCreator.New().firstName("John").lastName("Doe").create();
MicroStream.root().getPersons().addAll(Arrays.asList(create));
MicroStream.storageManager().storeAll(MicroStream.root().getPersons());`

**Person interface**
```
public interface Person extends Entity
{
        public String getFirstName();
	public String getLastName();
}
```

**Root class**

```
public class DataRoot
{
	Set<Person> persons = new HashSet<>();
	
	public DataRoot()
	{
		super();
	}

	public Set<Person> getPersons()
	{
		return this.persons;
	}

	public void setPersons(final Set<Person> persons)
	{
		this.persons = persons;
	}
}
```

**Comment by zdenek-jonas** [comment]
ok works. 
Automation test is ready. These tests will be extended.
