### ISSUE TITLE
UI-Gui - Small Integer als reference shown and bigger not.

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#107]
UI-Gui - Small Integer als reference shown and bigger not.

![image](https://user-images.githubusercontent.com/17253582/78884411-27689780-7a5b-11ea-9605-789de3978783.png)

**Comment by hg-ms** [comment]
Analysed and provided bugfix, test adapted to changes.

The issue was caused within one.microstream.storage.restadapter.ViewerBinaryPersistenceManager.Default.getStorageConstant(long) because the recieved object was not set as 'primitive' instance. Instead is was set as normal referenced object

**Comment by zdenek-jonas** [comment]
retest successful
![image](https://user-images.githubusercontent.com/17253582/79192833-beea3380-7e29-11ea-930c-541318a79e36.png)
