### ISSUE TITLE
Adding a second full backup funktion to Microstream

### ISSUE THREAD

**Issue by ZorgCK** [microstream-one/microstream#109]
Beside the continous backup our customers want a full backup every day, week or month. We tryed the "import / export" and "CRON Jobs" as solution for that. But in both there are problems and we can no longer use them.
The simplest solution would be a methode with a path parameter to copy the whole storage threadsave to a different folder.
A further solution would be a possibility to transfer the whole storage to an AWS S3 Bucket i could image something like a ByteStream return Method.

**Comment by tm-ms** [comment]
Duplicate of microstream-one/microstream-public#18
