### ISSUE TITLE
Restservice: Don't depend directly on EmbeddedStorageManager

### ISSUE THREAD

**Issue by m-stoer** [microstream-one/microstream#110]
Currently to use the Restservice for the RemoteStorageManager I have to wrap it in a dummy EmbeddedStorageManager (To give StorageRestServiceResolver.resolve(EmbeddedStorageManager)). Better would be to depend on one of the interfaces instead e.g. StorageSystem, StorageConnection etc.

**Comment by fh-ms** [comment]
The rest service now takes a `StorageManager` instead of `EmbeddedStorageManager`. To go further up (e.g. `StorageConnection`) is not possible.

**Comment by m-stoer** [comment]
Can we also change the StorageRestServiceSparkJava#New(EmbeddedStorageManager) method signature to New(StorageManager)? All the method does is to create a StorageRestAdapter that takes the StorageManager interface. So there should be no problem to change this as well.

**Comment by fh-ms** [comment]
Changed 
`StorageRestServiceSparkJava#New(EmbeddedStorageManager)`
to
`StorageRestServiceSparkJava#New(StorageManager)`
