### ISSUE TITLE
GUI Client login - after change the url gui needs two click to connect

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#112]
After change the URL on home page, gui needs two click to connect to server. 

First click, lost focus and second click connect.
When one click on the "Connect" Button for the first time, nothing happens. One must click again. 

Step to reproduce:
Open the GUI with login dialog.
Select the default URL from dropdown
Edit this URL and click direct on Button => connection will not be done. 
Try click again and then system try to connect.

**Comment by fh-ms** [comment]
Unfortunately it is an odd behaviour of Vaadin. When the ComboBox has the focus, the click on the button does not raise an event.

**Comment by zdenek-jonas** [comment]
Ok, when this behavior is default, then i close this issue.
