### ISSUE TITLE
Backup advanced storage configurations

### ISSUE THREAD

**Issue by hg-ms** [microstream-one/microstream#114]
Currently it is the users resposibility to backup any storage configurations that exceed the capabilities of the ConfigurationLoader.
The idea is to write all configured components (e.g CustomTypeHandlers) from the foundations to a human readable format

**Comment by fh-ms** [comment]
It is currently not possible to retrieve again all properties/values from an `EmbeddedStorageFoundation` used in the `Configuration`, because of missing getter methods in public API.

**Comment by fh-ms** [comment]
Implemented storage configuration exporter methods, which export an existing `one.microstream.storage.configuration.Configuration` into various formats.
See `Configuration#export...` methods.

**Comment by zdenek-jonas** [comment]
This issue will be tested in separate story.
