### ISSUE TITLE
Android - there are no File or Path for resources, such as refactoring.csv

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#117]
There are two possibility to get resource file in android. Assets and Raw resources. Both of them have  and Approach via InputStream. There are no possible to get Path or File instance for resources in Android. 

Thanks to this feature, it is not possible to easily use legacy type mapping using CSV files. Of course, one can read and pass the contents of this file directly as XGettingSequence. Unfortunately, this again means implementation in the internal api.

I suggest: In case of confirmation of interest in Android, implement this function with the InputStream parameter.

**Comment by tm-ms** [comment]
I enhanced the API with additional Persistence#RefactoringMapping variants to allow passing arbitrary strings from which the mapping shall be parsed.

I won't support passing IO ~Stream instances for two reasons:
1.) They are old IO means, long replaced by NIO.
2.) They are rather low-level mechanisms, including resource handling etc. Passing such low-level utility instances as public API is bad design, e.g. prone to conflicts with resource handling, etc.

Just read the string from the InputStream instead and pass it cleanly to the API.

**Comment by zdenek-jonas** [comment]
Naja... Android api is based on ziemlich alte Java. Ja eine Lösung mit String geht auch.

**Comment by zdenek-jonas** [comment]
Ok, with String works, i am ok with this solution
