### ISSUE TITLE
Communication host cannot be stopped

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#119]
Communication host cannot be stopped

`host.stop()` never finishes

Code example: 

```
package one.microstream.communication;

import one.microstream.com.ComChannel;
import one.microstream.com.ComClient;
import one.microstream.com.ComHost;
import one.microstream.com.binarydynamic.ComBinaryDynamic;
import one.microstream.meta.XDebug;
import org.junit.jupiter.api.AfterEach;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import java.nio.ByteOrder;

public class BasicComTest {
    private ComHost<?> host;
    private Thread t;

    @BeforeEach
    public void startServer() {
        t = new Thread(() -> {
            host = ComBinaryDynamic.Foundation()
                    .setHostByteOrder(ByteOrder.BIG_ENDIAN)
                    .setHostChannelAcceptor(hostChannel ->
                    {
                        hostChannel.send(new ComplexClassNew());

                        final Object o = hostChannel.receive();
                        XDebug.println("HOST RECEIVED: " + o.toString());
                    })
                    .createHost()
            ;

            // run the host, making it constantly listen for new connections and relaying them to the logic
            host.run();
        });
        t.start();

    }

    @AfterEach
    public void stopServer() {
        //System.out.println("is running: " +  host.isRunning());
        host.stop();
    }

    @Test
    public void receiveBasicObjectTest() {
        final ComClient<?> client = ComBinaryDynamic.Client();

        // create a channel by connecting the client
        final ComChannel channel = client.connect();

        final Object o = channel.receive();

        Assertions.assertNotNull(o, "Null Object received. ");

        channel.send("exit");

    }
}
```

**Comment by hg-ms** [comment]
At first glance the current ComHost implementation needs some redesign to support the desired behavior. In addition, the ServerSocket currently uses the Blocking mode.

**Comment by zdenek-jonas** [comment]
[java.network.programming.4th.edition.developing.networked.applications.pdf](https://github.com/microstream-one/microstream-private/files/4690960/java.network.programming.4th.edition.developing.networked.applications.pdf)
I have some ebook about Java Network Programming, unfortunately, is a little bit old.

**Comment by hg-ms** [comment]
There are three cases where blocking can occur:
1.	The hosts listens for incoming connections in one.microstream.com.ComConnectionListener.Default.listenForConnection()

2.	The host waits for client data
3.	The client waits for host data
Case 2 and 3 are related to the SocketChannel.read(..) calls.

In order to interrupt a blocking I/O operation the channel needs to be closed from another thread. 

To solve that issue two possible architectural changes could work:
1.	Change the current channel behavior from blocking to non-blocking mode.
2.	Implement multithreading for server and clients.

**Comment by hg-ms** [comment]
The host.stop method as been reworked and will stop the host if called from an other thread.

**Comment by zdenek-jonas** [comment]
fixed
