### ISSUE TITLE
SQL Types test for Oracle DB (and another DB systems also) is very slow

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#138]
I have set of test, this test create sample Data Object mostly with one class Members. This class with one members is saved and load from DB. Local takes this ms but in the Cloud or DB takes seconds. The size of this class is in bytes.

It must be optimized. 

![image](https://user-images.githubusercontent.com/17253582/88390410-91157300-cdb8-11ea-8684-e73b8497bb3b.png)
![image](https://user-images.githubusercontent.com/17253582/88390471-ab4f5100-cdb8-11ea-9807-96151f00dd39.png)
![image](https://user-images.githubusercontent.com/17253582/88390494-b2765f00-cdb8-11ea-8f11-53ca9c498b1c.png)

**Comment by fh-ms** [comment]
microstream-one/microstream-private#356 should increase initial performance

**Comment by fh-ms** [comment]
Maybe microstream-one/microstream-private#359 helps as well

**Comment by zdenek-jonas** [comment]
It helps, we are now between 4-10 seconds pro test. It is better but still slow. Docker is running on maximal CPUs and memory what i have on my PC.

**Comment by zdenek-jonas** [comment]
It has been tested on real project. The problem is on my PC and test structure. The first connection takes a lot of time.
