### ISSUE TITLE
java.util.Locale persisted erroneously

### ISSUE THREAD

**Issue by hg-ms** [microstream-one/microstream#14]
Reloading a persited java.util.Locale instance produces an errnous instance.
The reloaded instance is not initialized correctly.
The member "BaseLocale baseLocale" is null.

The member baseLocale is null because is declared transient, correctly causing it not to be stored.

It seems that this class needs a custom store and load handling.
The the Java default serialization stores fields of the transient member "baseLocale" and 
does some initializing during deserialization

**Comment by fh-ms** [comment]
Had the same issue in RapidClipse.
Best way to persist a Locale is to store the output of `toLanguageTag()`.
To restore use `Locale.forLanguageTag(String)`

**Comment by tm-ms** [comment]
> Had the same issue in RapidClipse.
> Best way to persist a Locale is to store the output of `toLanguageTag()`.
> To restore use `Locale.forLanguageTag(String)`

The language tag seems indeed to be a kind of string-based serialization of a Locale instance. So it should ("must"?) be enough to persist a Locale instance. (And if not, it's their fault :D).
So this should be a sufficient solution.

**Comment by tm-ms** [comment]
BinaryHandlerLocale implemented.

Generated TypeDictionary entry:
```
0000000000000000068 java.util.Locale{
	[char] languageTag,
}
```

`Locale.getAvailableLocales()` as stored, loaded, exported and converted by `MainTestStorageLocaleHandler`:
[java.util.Locale_68.csv.txt](https://github.com/microstream-one/microstream-private/files/3847071/java.util.Locale_68.csv.txt)

Funny enough:
Locale #0 in the array seems to be a kind of empty/zero element.
All its Strings are "".

And its language tag is ... naturally ... consequently ... "und". Riiight.
Probably a moron's way to express "undefined". Fits perfectly in the JDK.
