### ISSUE TITLE
Database initialization considerably slower since AFS

### ISSUE THREAD

**Issue by tm-ms** [microstream-one/microstream#155]
@JohannesRabauer reported that the "Bonus" Database (2,77 GB size, double digit millions of entities) takes 145 seconds to initialize with MicroStream version 3.1 instead of 31 seconds.

A similarily sized database has to be created to have its initialization time investigated.

**Comment by fh-ms** [comment]
Test with the BookStore demo yielded the same result. Most noticeable difference is the added java.nio.file.Files#exist calls in the AFS version, which consume actually more time than the reading itself.

![image](https://user-images.githubusercontent.com/53050506/91727467-0affff80-eba2-11ea-8784-4aa67959f8c1.png)

**Comment by tm-ms** [comment]
I'll look into removing the exists call.

**Comment by tm-ms** [comment]
I removed the following expensive calls:


AFile#exists inside AFile#ensureExists
This was a redundant expensive call just to avoid a lambda instantiation.
(...rather stupid)


AFile#ensureExists in AFile#size
#size can be called quite frequently by some algorithms and the exists call completely destroys its performance.
Instead, the using logic must call it precisely when needed.


AFile#ensureExists in StorageFile#internalOpenReading
This is the one from the call stack above.

Comment above the deactivated call:
---
This is too expensive (additional round trip on network calls               
and even on low-level implementation like JDK NIO).                         
So the file must be assumed to be still properly there after being created. 
Maybe it's even good to NOT ensure it since that recognizes erroneously     
missing files instead of swallowing the problem by silently compensating it.
---

AFile#ensureExists in StorageFile#internalOpenWriting
Basically the same as internalOpenReading, although this should not be as performance critical.
However, the rationale of comment applies here, too.



All other calls to AFile#exists are only caused by relatively "rarely" called logic.
Note that "rare" in this context means "not hundreds or thousands of times per second".
Typically actions like copying whole files, creating files, reading or writing the whole transactions file, type dictionary file, checking the lock file etc.
All of these should never occur more than, say, once per second at the most, so the relatively expensive #exists call is still rather fast in absolute terms.


Performance test for MainTestStorageExample
 
(note: the basic storage example does not use any Lazy references, so EVERYTHING is loaded at the beginning)
(also note: the times are on my computer and only make sense for comparing them)

~3 Million entities without fix:
Initialization time: 1.3 - 1.5 seconds
Loading time: 6.9 - 10.0 seconds (typically 7.0)

~3 Million entities with fix:
Initialization time: 1.3 - 1.5 seconds
Loading time: 6.6 - 11.0 seconds (typically 7.3)

Weird values.
The high values seem to be caused by lots of "performance noise" by all the other processes.
And probably the ~10 runs I made each are too few to get reliable data.
Maybe there is a slight improvment. Maybe not.
Logic-wise, there is definitely code skipped that is very expensive and was called very often.
Maybe the entity count is still too low.


So another test with ~9 Million entities (~500 MB database)
But only 3 runs each this time since the count is already higher.

~9 Million entities without fix:
Initialization time: ~6,4 seconds
Loading time: ~30 seconds

~9 Million entities with fix:
Initialization time: ~6,2 seconds
Loading time: ~30 seconds


Again, maybe a slight improvement, maybe not.
Intersting is: This database is about 1/5 the size of the one where the issue was reported.
5 times ~6,4 seconds is ... ~31 seconds.

This means:
I cannot reproduce the problem in the first place.
The fix definitely removed a lot of often-called expensive work.

I can't say or do anything more at the moment.
Please test again with the committed change.

**Comment by fh-ms** [comment]
Tests with BookStoreDemo now show considerable better performance. Compared to the pre-AFS version only a 0-5% slower performance can be observed. This should be good enough for now.

**Comment by JohannesRabauer** [comment]
Tested Version 4.0 with the same Database mentioned above and it worked just like before.
