### ISSUE TITLE
AFS ensureFilePath creates file in wrong folder

### ISSUE THREAD

**Issue by m-stoer** [microstream-one/microstream#163]
On current master (4f00dd845378204f6ccb82ac4b4ba07db7c879d2) when I execute the following example the file is generated in a subdirectory with the same name.
```java
NioFileSystem.New().ensureFilePath("file").ensureExists();
```
This snippet creates a file inside a folder, both called "file". This only happens if only one parameter is supplied. If I for example call ensureFilePath("dir", "file"), then a file called "file" is created inside a folder called "dir".

**Comment by tm-ms** [comment]
The cause for this should be findable pretty easily with a little debugging.

**Comment by zdenek-jonas** [comment]
ok works
