### ISSUE TITLE
Simplifiy usage of other java.nio.file based file systems

### ISSUE THREAD

**Issue by hg-ms** [microstream-one/microstream#165]
Inspired by  #https://github.com/microstream-one/examples/issues/23

Our current NioFileSystem implementation is currently tied hard to some static methods that prevent an easy replacement of the used java.nio.file based file-system like https://github.com/google/jimfs

Goal of this task is to make it more easy to replace the used java.nio.file based file-system.

**Comment by hg-ms** [comment]
Changes available at:
https://bitbucket.org/microstreamone/microstream/branch/feature/441-SimplifiyAlternativeNIOFileSystems

Tested with some filesystems:

https://github.com/google/jimfs                                     -> OK
https://github.com/marschall/memoryfilesystem           -> OK
https://github.com/cryptomator/cryptofs                       -> FAILED
Java 8 Zip File System                                                      -> FAILED


the crypto fs fails with
"java.lang.IllegalArgumentException: Path must be absolute but was PersistenceTypeDictionary.ptd"

zip file system fails with
"one.microstream.storage.exceptions.StorageException: Impossible store length:"

**Comment by hg-ms** [comment]
Usage example with jimfs:

The simplest case:
```
final FileSystem jimfs = Jimfs.newFileSystem();
EmbeddedStorageManager storage = EmbeddedStorage.start(jimfs.getPath("storage"));
```
Or create a StorageFileProvider:
```
final FileSystem jimfs = Jimfs.newFileSystem();
final StorageLiveFileProvider fileProvider = StorageLiveFileProvider.Builder(
	NioFileSystem.New(
		NioIoHandler.New(
			new NioPathResolver.Custom(jimfs))))
	.createFileProvider();
```

**Comment by zdenek-jonas** [comment]
For jimfs there are integration tests works. I close this issue. I will test these api later more precisely.
