### ISSUE TITLE
Add OSGi bundle headers to released jar file

### ISSUE THREAD

**Issue by fh-ms** [microstream-one/microstream#17]
In order to use MicroStream in OSGi environments it is necessary to ship the OSGi bundle headers within our jar files. This can be done with a maven plugin in the package phase of the build.

https://blog.osoco.de/2016/05/building-osgi-bundles-with-apache-maven/

**Comment by fh-ms** [comment]
Was a misunderstanding of the problem. Our modules don't have to be OSGi bundles itself. The issue is how the OSGi bundles import and export packages, so the bundle using MicroStream to persist stuff, must have access to the other bundles' content. So nothing we can do here, but OSGi projects must adopt to circumstances.

**Comment by fh-ms** [comment]
Issue came up again at JUG Augsburg today. In order to use external libraries in OSGi environments they need to add the header information by themselves. If we could include the header generation in our build, our modules could be used out of the box in OSGi environments.
Can be easily done with BND tools Maven plugin:
https://github.com/bndtools/bnd/tree/master/maven/bnd-maven-plugin

**Comment by hg-ms** [comment]
Have a look at our forum https://forum.microstream.one/?qa=104/osgi-metadata

Mr. Thomas Driessen provided a maven configuration.

**Comment by fh-ms** [comment]
Additionally to that we should provide a p2 deployment on our Nexus server. There should be a Maven plugin for that.

**Comment by fh-ms** [comment]
Added script for OSGi headers to default build.
In ./p2 the repository can be created with `mvn clean validate p2:site`

**Comment by zdenek-jonas** [comment]
Ok, repo is ready. URL: `https://repo.microstream.one/service/rest/repository/browse/update-site/`
to download for example: https://repo.microstream.one/repository/update-site/04.00.00-MS-
P2/

But the installation into eclipse creates another issue and eclipse crashed.
https://github.com/microstream-one/microstream-private/issues/446

**Comment by zdenek-jonas** [comment]
![image](https://user-images.githubusercontent.com/17253582/100857833-77ceb280-348d-11eb-9e83-f06b0b07ffa4.png)

**Comment by zdenek-jonas** [comment]
![image](https://user-images.githubusercontent.com/17253582/100859316-6090c480-348f-11eb-8330-864540d4b492.png)
Unsigned software.

**Comment by zdenek-jonas** [comment]
fixed
