### ISSUE TITLE
Reading entities from storage files is broken for some cases: Fields of entities are filled with wrong content, entities are unusable

### ISSUE THREAD

**Issue by JMMSW** [microstream-one/microstream#172]
There is a project with a "Screening" entity class.
This class was changed multiple times. (According to PersistenceTypeDictionary: 5x, there are six versions)

The two last changes are:
A) adding two fields ("created", "createdBy")
B) adding another two fields and move the two fields created in step A)

Starting the storage now does not throw errors. 

But some of the "Screening" objects created before last change cannot be used any more:
**The fields and field contents are not in sync.** 
E.g. the "screeningDate" field of type "LocalDate contains a String. Accessing the field's value results in errors like 
"java.lang.IncompatibleClassChangeError"

More examples of wrong field contents:
![2021-03-03_Screenshot_Debugger_Variables](https://user-images.githubusercontent.com/67729087/109833052-3e027900-7c41-11eb-8308-e69f23b006f4.PNG)

PersistenceTypeDictionary is attached, Storage and example project can be provided.
[PersistenceTypeDictionary.zip](https://github.com/microstream-one/microstream-private/files/6077349/PersistenceTypeDictionary.zip)

**Comment by fh-ms** [comment]
Seems like a duplicate of microstream-one/microstream-private#504, please check.

**Comment by zdenek-jonas** [comment]
According the description is this bug really duplicate of microstream-one/microstream-private#504 . It will be released soon. When this after release still not works as designed, please reopen this issue.
