### ISSUE TITLE
java.time.ZoneOffset persited state not correctly loaded

### ISSUE THREAD

**Issue by hg-ms** [microstream-one/microstream#173]
related to our Forum: https://microstream.one/support/forum/topic/70/page/1/

The class ZoneOffset has the field “private final transient String id” that is not persisted due to the transient modifier. After loading that class, the field “id” is not set and stays “null” as it is only set in the constructor. This causes the getter #getId to return null.

Note:
The issue exists allready within java 8

**Comment by zdenek-jonas** [comment]
We have a little bit more problems with Calendar. 
Current test call equals, but some members are not relevant for equals.
This build shows the test:
Original is original class
And copy is original saved into microstream and load from storage back:

There are some other types to check:

- [ ] GregorianCalender - toString() raise NPE
- [x] Clock - after load is SystemClock[null]
- [x] OffsetDateTime
- [x] OffsetTime
- [x] ZoneOffset

![image](https://user-images.githubusercontent.com/17253582/110469169-99b58200-80d9-11eb-8a7e-8a9319ba9c68.png)

**Comment by fh-ms** [comment]
Added a type handler for ZoneId, which fixes the problems with the offset and clock types.

The old calendar types are a different (extinct) animal, which shouldn't be used anymore, anyway.

**Comment by zdenek-jonas** [comment]
Ok..
