### ISSUE TITLE
LegacyTypeMapping - remove class member causes to shift values to another members

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#174]
Consider followings objects:

```
public class DellPerson {

    private String firstName;
    private String lastName;
    private String fullName;
    private Map<String, String> attributes = new HashMap<>();
    private Integer age = null;
    ...
```
```
public class DellPerson2 {

    private String firstName;
    private String fullName;
    private Map<String, String> attributes = new HashMap<>();
    private int age = 2;
    ...
```
One would expect the "legacy type mapping" function to recognize that the "lastName" variable has been removed.

Instead of this a receive following message:
```
java.lang.ClassCastException: class java.util.HashMap cannot be cast to class java.lang.Integer (java.util.HashMap and java.lang.Integer are in module java.base of loader 'bootstrap')

	at one.microstream.persistence.binary.types.BinaryValueTranslators.copyIntegerTo_int(BinaryValueTranslators.java:1209)
	at one.microstream.persistence.binary.types.Binary.updateFixedSize(Binary.java:2055)
	at one.microstream.persistence.binary.types.AbstractBinaryLegacyTypeHandlerReflective.updateState(AbstractBinaryLegacyTypeHandlerReflective.java:98)
	at one.microstream.persistence.binary.types.AbstractBinaryLegacyTypeHandlerReflective.updateState(AbstractBinaryLegacyTypeHandlerReflective.java:1)
	at one.microstream.persistence.binary.types.BinaryLoader$Default.buildInstances(BinaryLoader.java:447)
        ...
```

so the Microstream map this fields according the order and not a name, this is a reason why he tries to map integer to HashMap.

For this problem gibt es finished test in project microstream-test
`src/test/java/test/microstream/legacy/delete/DeleteFieldTest.java`
This test is disabled for now, just remove @disabled annotation

**Comment by fh-ms** [comment]
Regression was introduced with enum handling.
Value-skipping BinaryValueSetters are discarded before handing them over to the LegacyTypeHandler. Then the deleted field's binary data isn't skipped properly, which caused the shifting of values.
Fixed and tested, also with enums. 
Please check the automated tests to handle these cases thoroughly.

**Comment by zdenek-jonas** [comment]
First test cannot be done, the test hangs. I just prepare the mictrostream build in Jenkins for this branch:
https://jenkins.microstream.one/job/bugfix_FH_priv504_LegacyTypeMapping_remove_class/job/microstream-ci/

and also prepare branch for Microstream-test project:
priv504_legacy_type_mapping

Just download and launch test:
src/test/java/test/microstream/legacy/delete/DeleteFieldTest.java

Test hangs in storage.shutdowns method.

**Comment by zdenek-jonas** [comment]
TODO: After fix inform Johannes Rabauer

**Comment by zdenek-jonas** [comment]
Ok, Tests laufen wieder...

**Comment by zdenek-jonas** [comment]
Test are green, add new Enum and CSV tests into Test Project.
