### ISSUE TITLE
Restructure: Restadapter: one.microstream.storage.restservice.exceptions.StorageRestServiceNotFoundException: No StorageRestServer implementation found

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#176]
After restructure does not work Restadatper:

```
one.microstream.storage.restservice.exceptions.StorageRestServiceNotFoundException: No StorageRestServer implementation found
	at one.microstream.storage.restservice.types.StorageRestServiceResolver.resolve(StorageRestServiceResolver.java:36)
	at one.microstream.ui.StorageProvider.startStorage(StorageProvider.java:30)
	at one.microstream.ui.step.StorageSteps.lambda$new$1(StorageSteps.java:24)
	at ✽.the storage with LongListTestData is started(classpath:one/microstream/ui/addNewType.feature:4)
```

vmt test `vmt/restservicetests` failed too:

![image](https://user-images.githubusercontent.com/17253582/114012773-0ce01e80-9867-11eb-8854-007026bc7e86.png)

**Comment by zdenek-jonas** [comment]
Note: The same problem is also by Caching. Fix of this issue then apply also for cache and also test togehter.

**Comment by hg-ms** [comment]
The services had not been found because the META_INF/services had not been included in the final jars as soon as the the LICENSE file is added as resource. As fix i added the "src/main/resources" as additional resource-directory

**Comment by hg-ms** [comment]
~~An addional problem:
java -jar microstream-storage-restclient-app-04.02.00-MS-GA-SNAPSHOT.jar
**kein Hauptmanifestattribut,** in microstream-storage-restclient-app-04.02.00-MS-GA-SNAPSHOT.jar~~

**Comment by hg-ms** [comment]
And one more exception at runtime:
java.lang.IllegalStateException: The target component 'class one.microstream.storage.restclient.app.ui.ConnectView' has no registered route

Reason:
Vaadin does not scan other packages the the application's one for components that shall get a route

Solution:
```
@SpringBootApplication
@EnableVaadin("one.microstream.storage.restclient.app.ui")
public class Application extends SpringBootServletInitializer
```

**Comment by zdenek-jonas** [comment]
Ok works
