### ISSUE TITLE
Option to create a full backup

### ISSUE THREAD

**Issue by tm-ms** [microstream-one/microstream#18]
The initial, straight forward, simple and not very efficient backup strategy was to simply copy all storage files to a target directory via a StorageTask. The WIP project contains a `StorageBackupHelper` class for that that contains a consolidated tiny API for what was initially a rather lengthy manual util code. To the best of my knowledge, the `StorageBackupHelper` class has never been used, however.

On a technical level, this type of backup creation has actually been completely replaced
by the continuous backup functionality (see `StorageConfiguration#backupSetup` or issue microstream-one/microstream-private#61).
Also see issue microstream-one/microstream-private#17.

However, it turned out that on a psychological level, customers still want a "full backup" functionality because they do not fully trust a continuous backup or it hasn't been properly explained to them or whatever the reason might be. The absence of problems with the continuous backup plays no role in this, they simply want a "backup everything now" command.
So instead of copying only new files as they get created and filled, there's still need for a variant
that copies ALL files, no matter how inefficient, redundant or unnecessary that is.

As a consequence, the class `StorageBackupHelper` must be tested and afterwards be moved to a productive project, maybe even in the EmbeddedStorageManager type directly. The details for this are yet to be determined.

**Comment by hg-ms** [comment]
Tested the StorageBackupHelper class:
Using this class allows to create full backups. This helper class is working but i would suggest it move its functionality into the StorgeManager for easy usage. Currently the StorageBackupHelper forces the user to keep an explicit reference to the StorageFoundation tio initialize the StorageBackupHelper.

The export of the channels data files is already available in the StorageManager (see one.microstream.storage.types.StorageConnection.exportChannels(StorageIoHandler, boolean))

The export of the type dictionary is currently not available from the StorageManager but may be added quite easy. Maybe the existing PersistenceTypeDictionaryExporter can be utilized.

**Comment by tm-ms** [comment]
CK has stressed that having such a feature in the public API would be very helpful.

**Comment by fh-ms** [comment]
Added issueFullBackup methods in StorageConnection (EmbeddedStorageManager).

**Comment by zdenek-jonas** [comment]
ok, works.
