### ISSUE TITLE
Validate Channel Folders to Channel Count 

### ISSUE THREAD

**Issue by tm-ms** [microstream-one/microstream#192]
When the storage is initialized, the channel folders contained in the storage directory should be validated against the configured channel count and throw a meaningful exception on a mismatch.

Otherwise, starting a storage with a lower configured channel count than there are channel folders can cause confusing and unsettling exceptions, for example `No roots found for existing data`.

**Comment by hg-ms** [comment]
feature branch:
https://github.com/microstream-one/microstream/tree/feature/ValidateChannelFolders-192

**Comment by zdenek-jonas** [comment]
ok tested
