### ISSUE TITLE
Arithmetic bug in StorageDataFileValidator#validateFile

### ISSUE THREAD

**Issue by tm-ms** [microstream-one/microstream#194]
A backup validation exception reported by JM showed that there must be a low-level memory address arithmetic error in `StorageDataFileValidator#validateFile` or actually probably in `BinaryEntityRawDataIterator#iterateEntityRawData` which is used by the validator.

Inner-most cause exception:
```
one.microstream.storage.exceptions.StorageException: Uncompletable validation: -3458764513820540804 remaining bytes of 124 total cannot be validated in file /backup/rollingBackup/channel_0/channel_0_2653.dat at offset 1302528
  at one.microstream.storage.types.StorageDataFileValidator$Default.validateFile(StorageDataFileValidator.java:130)
  at one.microstream.storage.types.StorageBackupHandler$Default.copyFilePart(StorageBackupHandler.java:455)
```

This problem is not critical since the iterator is only used for validation and the exception only prevents bringing an existing backup up to date with the latest store, so as a workaround, the backup just has to be deleted and replaced by the original storage.

But in general, this has to be fixed, of course.

**Comment by hg-ms** [comment]
fixed with https://github.com/microstream-one/microstream/pull/273
