### ISSUE TITLE
TypeDictionary not recreated after deleting backup directory

### ISSUE THREAD

**Issue by hg-ms** [microstream-one/microstream#197]
If the backup directory content is deleted the type dictionary file ist not recreated on the next startup. 

Observed with 02.02.01-MS-GA and  02.03.00-MS-GA-SNAPSHOT

The storage gets started with:

> 		EmbeddedStorageManager storage = Configuration.Default()
>			.setBaseDirectory(workDir.toString())
>			.setBackupDirectory(bkupDir.toString())
>                     .createEmbeddedStorageFoundation()
>                     .start();

1. Create storage with content, store something and stop
2. delete backup directory
3. restart storage:
	**==> type dictionary will not be recreated in backup dir**

**Comment by zdenek-jonas** [comment]
Unfortunately, this has another scenario where it does this problem.
If I start an application with an existing storage and with another backup directory (for example with a date), the type dictionary is not transferred to this new backup directory.

**Comment by fh-ms** [comment]
PersistenceTypeDictionaryFileHandler has a PersistenceTypeDictionaryStorer as a writeListener, which is provided by the StorageBackupFileProvider. But the writeListener only gets called when the type dictionary changes. It is not included in the initial synchronization of the backup.
