### ISSUE TITLE
GUI Client is not responsive

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#198]
GUI Client is not responsive

It is a question here: Must be really responsive?
I create this issue to discuss it. 

![image](https://user-images.githubusercontent.com/17253582/79329396-07801a80-7f18-11ea-8823-f389d5dbb051.png)
![image](https://user-images.githubusercontent.com/17253582/79330101-36e35700-7f19-11ea-9fe0-4e7669e49782.png)

![image](https://user-images.githubusercontent.com/17253582/79330047-216e2d00-7f19-11ea-820b-eb3b14dfafca.png)

**Comment by fh-ms** [comment]
If we will provide an UI for mobile devices, we should consider a redesign. The TreeGrid, for example, is not user-friendly at all on small screens.

**Comment by zdenek-jonas** [comment]
This View is for Debug purposes only. Debug on a mobile device is very unlikely. I am closing this issue as author.
