### ISSUE TITLE
Not usable with Java module system

### ISSUE THREAD

**Issue by Dudeplayz** [microstream-one/microstream#2]
I've tried to create a test project to use microstream. I want to use the module system, but this isnt possible due the following error:
```
Error occurred during initialization of boot layer
java.lang.module.ResolutionException: Modules persistence and persistence.binary export package one.microstream.persistence.lazy to module test.module1
```
It seems, that there is no module-info for microstream because it is written in Java 8 and the maven dependency is resolved to multiple jars which are containing the same package names.

**Comment by fh-ms** [comment]
The new release 2.2 contains a fat jar artifact, which is compatible with the Java module system.
```
<dependency>
    <groupId>one.microstream</groupId>
    <artifactId>all</artifactId>
    <version>02.02.00-MS-GA</version>
</dependency>
```
