### ISSUE TITLE
Check different NIO FileSystemProviders

### ISSUE THREAD

**Issue by fh-ms** [microstream-one/microstream#20]
After microstream-one/microstream-public#19 is done we can check if various file system providers are sufficiently implemented for our needs.

In memory file systems
- https://github.com/marschall/memoryfilesystem
- https://github.com/google/jimfs

Cloud drive adaptors
- https://github.com/Upplication/Amazon-S3-FileSystem-NIO2
- https://github.com/elerch/Amazon-S3-FileSystem-NIO2
- https://github.com/seqeralabs/nxf-gsfs
- https://github.com/nextflow-io/jdk7-dxfs

**Comment by fh-ms** [comment]
[Amazon Elastic File System](https://aws.amazon.com/de/efs/) seems a better fit than S3. It can be directly mounted and used like a local file system. S3 on the other hand is more a key value store than a file system, it doesn't support append operations, for example.

**Comment by tm-ms** [comment]
Adam Bien gave us some quick hints about technologies called "ceph" and "rook" that could be used like a native FileSystem by application, but are actually clustered. Or something like that. It was really quick ...
