### ISSUE TITLE
Deep copy utility

### ISSUE THREAD

**Issue by fh-ms** [microstream-one/microstream#207]
Many customers and our inhouse project teams as well, stated that a deep copy utility for object graphs would come in very handy, for various use-cases. This should be pretty easy to do given our serialization capabilities.

**Comment by fh-ms** [comment]
To finalize this feature, we should add proper documentation.

**Comment by zdenek-jonas** [comment]
https://docs.microstream.one/manual/storage/storing-data/deep-copy.html
