### ISSUE TITLE
Support ObjectStreamFields besides transient keyword

### ISSUE THREAD

**Issue by fh-ms** [microstream-one/microstream#214]
Our default PersistenceFieldEvaluator checks if a field is not transient. The Java serialization spec also has another method: ObjectStreamFields:
https://docs.oracle.com/javase/8/docs/platform/serialization/spec/serial-arch.html#a6250

This is an addition we should consider.

**Comment by hg-ms** [comment]
we have a FieldEvaluator for that => closed
