### ISSUE TITLE
Support for records and sealed types with JDK 16

### ISSUE THREAD

**Issue by marcelbaumann** [microstream-one/microstream#223]
The current microstream version crashes if records are used in JDK 15 (preview records) or preview version of JDK 16 (records).

It would be nice if next versions of microstream supports records and sealed types. JDK 16 shall be officially released in less than 3 weeks.

**Comment by zdenek-jonas** [comment]
Support for records is implemented in release 5. This closes this issue.
If you have a specific problem, please open a new one.
