### ISSUE TITLE
Set.of() not handled properly

### ISSUE THREAD

**Issue by oscheffers** [microstream-one/microstream#244]
## Environment Details
* MicroStream Version: 05.00.02-MS-GA
* JDK version: adopt-openjdk-16 (version 16.0.1)
* OS: Windows 10 Pro 64-bit
* Used frameworks: Microstream only

## Describe the bug
When I create a immutable leaf in my object node that contains a Set created by Set.of(), it is not read back properly. In my case I used a Set of Role enums for a user, but I made an example here with just String to demo the problem.

The following code works properly the first time when there is no data-store yet. But when restarted, Microstream starts to read back the Set and sees an additional object of type java.lang.Object as first element in the Set. So even though I expect one entry in the Set, I get back two and one is of the wrong type. In my actual application that caused a ClassCastException.

Code to reproduce:

```
import java.util.Set;
import one.microstream.storage.embedded.types.EmbeddedStorage;
import one.microstream.storage.embedded.types.EmbeddedStorageManager;

public class App {
   private static Set<String> root = Set.of("My String");

   public static void main(final String[] args) {
      EmbeddedStorageManager storageManager = EmbeddedStorage.start(root);
      System.out.println("# items: " + root.size());

      storageManager.storeRoot();
      storageManager.shutdown();
   }
}
```

![afbeelding](https://user-images.githubusercontent.com/14818355/133601513-5098fc50-f05a-450a-ac03-3fc410979bd0.png)

**Comment by fh-ms** [comment]
The implementations of immutable collections in the JDK are a bit -  let's call them special. We probably need to implement specialized type handlers for them. 
@zdenek-jonas please confirm

**Comment by oscheffers** [comment]
Just confirmed List.of() has comparable behavior (additional java.lang.Object at the end of the list). Map.of() seems to work fine.

**Comment by hg-ms** [comment]
I can reproduce the issue with AdoptOpenJDK-16.0.1+9
but not with AdoptOpenJDK-11.0.11+9

**Comment by zdenek-jonas** [comment]
I just wrote a vm test. After one hour we will know exactly, with versions of JVM have this problem.

EDIT: It happens from JAVA 15

**Comment by hg-ms** [comment]
@zdenek-jonas I wrote handlers for the affected classes available in [branch Set12-List12-TypeHandlers](https://github.com/microstream-one/microstream/tree/Set12-List12-TypeHandlers). Maybe you can do some extended testing before I create a PR.
The handlers should be compatible for all java versions

**Comment by zdenek-jonas** [comment]
Already added. 

Documentation, how to use it:
https://docs.microstream.one/manual/storage/addendum/specialized-type-handlers.html
