### ISSUE TITLE
Logging

### ISSUE THREAD

**Issue by fh-ms** [microstream-one/microstream#293]
To achieve better useability we will add logging to the core modules.

We only log against a facade (slf4j), not a logger implementation to provide the best flexibility for our users.

See branch [feature/logging_slf4j](https://github.com/microstream-one/microstream/tree/feature/logging_slf4j)

Feel free to comment on this issue, to collect ideas where logging can be of interest.

**Comment by fh-ms** [comment]
- [x] Lifecycle of EmbeddedStorageManager
- [x] Lifecycle of StorageSystem
- [x] Lifecycle of StorageChannels
- [x] BinaryStorer actions (register, store, commit)
- [x] BinaryLoader actions
- [x] Lazy Loading
- [x] Lifecycle of LazyReferenceManager
- [x] GC actions
- [x] Backup
- [x] Configuration creation
- [ ] AFS

**Comment by hg-ms** [comment]
- [x] TypeHandler creation/registration
- [x] LegacyTypeHandler creation/registration
- [x] LegacyTypeMapping
- [x] Housekeeping

**Comment by hg-ms** [comment]
- [x] Logging the mircostream version at startup would be fine too

**Comment by zdenek-jonas** [comment]
https://github.com/microstream-one/microstream/issues/196
There is another issue with logging. Just to write actual configuration into the log. 
- [x] Cache

**Comment by fh-ms** [comment]
Need to specify in detail what could be logged in AFS.
