### ISSUE TITLE
Channel data files grow continually

### ISSUE THREAD

**Issue by 54446776** [microstream-one/microstream#298]
Running a simple persistent sequence id program, data direcotry size grows to 88.3M. Run program multi times,  data direcotry size keep growing. Oldest dat files can't be GC. 

Do I use MicroStream correctly?
(Mac M1, Java 17, 07.00.00-MS-GA-SNAPSHOT)

```java
public class TestSeq2
{
  public static void main(String[] args) throws InterruptedException
  {
    EmbeddedStorageManager storageManager = MicroStreamUtils.embeddedStorageManager.apply("storage_seq2.yaml");

    DummySeq seq;
    if (storageManager.root() == null) {
      seq = new DummySeq();
      SimpleRoot<Object> root = new SimpleRoot<>(seq);
      storageManager.setRoot(root);
      storageManager.storeRoot();
    } else {
      SimpleRoot<Object> root = (SimpleRoot<Object>) storageManager.root();
      seq = (DummySeq) root.ref;
    }

    long start = System.currentTimeMillis();

    long count = 1_000_000;
    long batchSize = 50_000;

    long iStart = seq.id + 1;
    long iStop = count + seq.id;
    for (long i = iStart; i < iStop; i++) {
      seq.id = i;
      storageManager.store(seq);

      if (i % batchSize == 0) {
        long now = System.currentTimeMillis();
        double avg = (now - start) / (double) i;
        System.out.printf("count: %d, avg: %.4fms\n", i, avg);
      }
    }

    System.out.printf("i: %d, seq id: %d\n", iStop - 1, seq.id);
  }
}
```

```java
public class SimpleRoot<T>
{
  final T ref;

  public SimpleRoot(T ref)
  {
    this.ref = ref;
  }
}
```

```java
public class DummySeq
{
  Long id = 0L;
}
```

```java
public class MicroStreamUtils {
  static Function<String, EmbeddedStorageManager> embeddedStorageManager = (yamlConfigFilePath) -> {
    var foundation = EmbeddedStorageConfiguration.load(
            ConfigurationLoader.New(yamlConfigFilePath),
            ConfigurationParserYaml.New()
    ).createEmbeddedStorageFoundation();

    foundation.onConnectionFoundation(BinaryHandlersJDK8::registerJDK8TypeHandlers);

    return foundation.createEmbeddedStorageManager().start();
  };
}
```

```yaml
storage-directory: "/tmp/test_microstream/data_seq2"
channel-count: 1
housekeeping-interval: 40
```

**Comment by hg-ms** [comment]
The behavior is mainly caused by the (currently) disabled garbage collection in the storage entity cache. You can enable/disable it with the static method `StorageEntityCache.Default.setGarbageCollectionEnabled(true)` 
and force a gc run with `one.microstream.storage.types.StorageConnection.issueFullGarbageCollection()` 
(The method setGarbageCollectionEnabled is marked as deprecated because java 8 has no experimental annotation)

**Comment by 54446776** [comment]
Is there any plan that storage-level gc will be ready for production?

// (24.11.2017 TM)TODO: there seems to still be a GC race condition bug, albeit only very rarely.
private static boolean experimentalGcEnabled = false;

/!\ EXPERIMENTAL /!\ Storage-level garbage collection is an unfinished feature with a still tiny race condition problem that can cause the database to be ruined occasionally.
public static void setGarbageCollectionEnabled(final boolean enabled) {
  experimentalGcEnabled = enabled;
}

**Comment by hg-ms** [comment]
We’re working on that issue. The release 06.01.00-MS-GA and 06.00.00-MS-GA already cointain several changes related to it. But until we are sure the gc related problem is solved we will not enable it by default and keep the API experimental.
We are optimistic that we can remove those warnings in one of the next releases and promote that API to a regular one.

**Comment by 54446776** [comment]
Thx hg-ms.
