### ISSUE TITLE
Typo in RuntimeException for memory quota outside valid range

### ISSUE THREAD

**Issue by belu** [microstream-one/microstream#3]
When providing an invalid memory quota (e. g. < 0) to `Lazy.Checker()` a `RuntimeException` is thrown:

`Caused by: java.lang.RuntimeException: Memory quora must be in the range [0.0; 1.0].`

It should state `Memory quota` and not `Memory quora`.

**Comment by fh-ms** [comment]
Fixed, thanks for pointing out.
