### ISSUE TITLE
Ticket J213: Enum not correctly loaded

### ISSUE THREAD

**Issue by hg-ms** [microstream-one/microstream#30]
Bug report from support ticket :  [#j213](https://microstream.one/back/tickets/view/3)

The reported bug is reproduceable using Microstream 02.00.01-MS-GA-SNAPSHOT.

possibly related to: microstream-one/microstream-public#28 

Summary:
During the enum loading in the reported ticket the enum's field "farbe" is overwritten by the enums name.

Output form the tickets code is :
Gebäude: HAUS
Farbe:   HAUS
Farbe:   null

Expected is:
Gebäude: HAUS
Farbe:   ROT
Farbe:   ROT

Analysis:
BinaryHandlerGenericEnum.Update(..) calls AbstractBinaryHandlerReflective.Update(..). Here bytes.updateFixedSize(..) is called to update the “farbe” reference member. 
Binary.updateFixedSize(..) uses the loadItemEntityContentAddress(..) to determine the source address. This call returns the address of the enumerations name, which is the first content element.

Maybe a dummy setter could be added for the "name" field to take It's offset into account.

> Fehler bei Verwendung von Enum in Enum
> Hallo zusammen,
>
> sorry, wenn ich direkt noch ein Ticket zum Thema Enum aufbaue. Ich habe schon seit ein paar
> Wochen ein Mysterium, das ich jetzt erst lösen und mit Microstream in Verbindung bringen konnte.
> 
> Angenommen ich baue mir ein simples Enum auf:
> 
> public enum Farbe {
> 	ROT, BLAU;
> }
> 
> 
> 
> Dies verwende ich nun in einem anderen Enum:
> 
> public enum Gebaeude {
> 	HAUS(Farbe.ROT), KIRCHE(Farbe.BLAU);
> 
> 	public Farbe farbe;
> 
> 	private Gebaeude(Farbe farbe) {
> 		this.farbe = farbe;
> 	}
> }
> 
> 
> 
> (Mein eigentlicher Code ist deutlich komplexer und fachlich anders, ich habe es nur zur Fehlerbeschreibung vereinfacht.)
> 
> Nun verwende ich das zweite Enum direkt in meinem Datenobjekt:
> 
> public class Data {
> 	public Gebaeude gebaeude;
> }
> 
> 
> 
> Schließlich erstelle ich einen neuen Storage:
> 
> Data root = new Data();
> 		EmbeddedStorageManager storage = EmbeddedStorage.start(root);
> 		root.gebaeude = Gebaeude.HAUS;
> 		storage.store(root);
> 
> 
> 
> Wenn ich diesen Storage nun auslese, wird es seltsam - um nicht zu sagen fehlerhaft:
> 
> Data root = new Data();
> 		EmbeddedStorageManager storage = EmbeddedStorage.start(root);
> 
> 		// Ausgabe HAUS - Hier ist noch alles okay.
> 		System.out.println("Gebäude: " + root.gebaeude);
> 
> 		// Ausgabe HAUS - Hier wird es seltsam.
> 		System.out.println("Farbe:   " + root.gebaeude.farbe);
> 
> 		// Ausgabe null - Das ist absolut unverständlich.
> 		System.out.println("Farbe:   " + root.gebaeude.farbe.name());
> 
> 
> 
> Ich verwende übrigens folgende Dependencies:
> 
> <dependency>
>       <groupId>one.microstream</groupId>
>       <artifactId>storage.embedded</artifactId>
>       <version>02.00.00-MS-GA</version>
>     </dependency>
> 
> 
> 
> Vielleicht liegt der Fehler auch bei mir? Dann vorab Entschuldigung für das Missverständnis.
> 
> Schöne Grüße und Danke für's Draufschauen,
> christian packenius.

**Comment by tm-ms** [comment]
Fixed and tested in branch bugfix/Minor_Bugfix_Batch.
