### ISSUE TITLE
Insufficient Documentation for StorageManager.storeRoot()

### ISSUE THREAD

**Issue by hg-ms** [microstream-one/microstream#304]
The Manual and JavaDoc related to the method storageManager.storeRoot() may be misleading regarding its usage. We should explicitly state that multiple calls of “storeRoot()” won’t update the whole object graph as storeRoot() also uses the default Lazy-Store behavior.

See:
https://docs.microstream.one/manual/storage/getting-started.html
https://docs.microstream.one/manual/storage/root-instances.html
And JavaDoc of one.microstream.storage.types.StorageManager.storeRoot()

**Comment by fh-ms** [comment]
Fixed with #452
