### ISSUE TITLE
Add Spring repository function

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#31]
In Spring Data exists repository concept: 
https://docs.spring.io/spring-data/jpa/docs/1.5.0.RELEASE/reference/html/jpa.repositories.html

It allow me to generate Query in DB only just writing one method in one interface. 
Some functions are implemented by default. This is very comfort to use for developers. 

Sample from Doku: [Spring repo ref](https://docs.spring.io/spring-data/data-commons/docs/1.6.1.RELEASE/reference/html/repositories.html)
```
public interface PersonRepository extends Repository<User, Long> {

  List<Person> findByEmailAddressAndLastname(EmailAddress emailAddress, String lastname);

  // Enables the distinct flag for the query
  List<Person> findDistinctPeopleByLastnameOrFirstname(String lastname, String firstname);
  List<Person> findPeopleDistinctByLastnameOrFirstname(String lastname, String firstname);

  // Enabling ignoring case for an individual property
  List<Person> findByLastnameIgnoreCase(String lastname);
  // Enabling ignoring case for all suitable properties
  List<Person> findByLastnameAndFirstnameAllIgnoreCase(String lastname, String firstname);

  // Enabling static ORDER BY for a query
  List<Person> findByLastnameOrderByFirstnameAsc(String lastname);
  List<Person> findByLastnameOrderByFirstnameDesc(String lastname);
}
```
Link to Spring [source code JPA Repo](https://github.com/spring-projects/spring-data-jpa/tree/master/src/main/java/org/springframework/data/jpa/repository)

**Comment by fh-ms** [comment]
This is realizable with flat data structures, but hardly doable with object graphs.
