### ISSUE TITLE
Reduce StorageEntity memory consuming

### ISSUE THREAD

**Issue by 54446776** [microstream-one/microstream#335]
## Backgroup

Let see a situation: 
**Database size:** is 271M(build with garbage collection)
➜  storage_db tree -h                           
[ 128]  .
├── [ 17K]  PersistenceTypeDictionary.ptd
└── [ 128]  channel_0
    ├── [271M]  channel_0_1.dat
    └── [ 170]  transactions_0.sft
1 directory, 3 files

**Heap size:** just load database without others framework(no spring ...
Used heap: 472M(after manual jvm gc)
one.microstream.storage.types.StorageEntity$Default	328,551,808 B (64.6%)	5,133,622 (60.8%)
this.is.myown.class	2,300,208 B (0.4%)	47,921 (0.6%)

## Problem
1.  StorageEntity instances consume up to 65% of total used heap memory.
2. StorageEntity instances consume much more memory than my own class instances(0.6%), payload is too much.
3. StorageEntity instances can't gc by jvm until EmbeddedStorageManager is closed.
4. As ms database size growing, StorageEntity instances memory consuming grow faster.
5. All StorageEntity instances loaded into heap(a whole db), normal obj references(String str;) and Lazy reference(Lazy\<String\> str;), which make Lazy reference less useful.
   (1 StorageEntity for 1 lazy ref, StorageEntity loaded into heap anywhere and StorageEntity use more memory than your own object)

## Expected solution
1. Sub object graph under Lazy reference(Lazy<Object> subGraph) should not be loaded into heap at database startup, only be loaded on demand.
2. No StorageEntity instance will be created for object within lazy sub object graph, until it's loaded.
3. StorageEntity instance can be gc(by JVM) after the whole lazy sub object graph is gc by JVM.
4. Reduce StorageEntity heap size consuming if it's possible.

**Comment by hg-ms** [comment]
The memory is occupied by the StorageEntitiyCache. In the current versions that cache has a bug that prevents it from removing deleted entries. The beta - version 07.00.00-MS-beta1 has a fix for that.
With that fix and the storage garbage collection enabled (StorageEntityCache.Default.setGarbageCollectionEnabled(true);) can also configure the StorageEntitiyCache and the Housekeeping. Please see https://docs.microstream.one/manual/storage/configuration/housekeeping.html.
With the default settings entities may stay cached very long (one day or more depending on their size).
This also applies to Lazy references…
In addition, you may consider two important aspects when using Lazy references.
They require 240 Bytes of memory even if not loaded. Using lazies with small objects therefore may cause a lot of overhead.
If the referent of a lazy can be reached by non-lazy reference chains from the storage root it is always loaded. Visa verse it can’t be unloaded if there is any other live object referencing to it.

**Comment by 54446776** [comment]
Let's see codes. After obj2 lazy reference cleared, StorageEntity$Default consuming memory unchange.

What I expect:

1.  StorageEntity$Default for the list(and the list elements) instances get recycled after root.obj2.clear();
2. if invoke root.obj2.get() later, the list get loaded into StorageEntityCache again.

```java
public class TestStoreEntityLazy
{
  public static void main(String[] args) throws InterruptedException
  {
    String dbPath = "/tmp/" + TestStoreEntityLazy.class.getSimpleName();

    StorageEntityCache.Default.setGarbageCollectionEnabled(true);

    EmbeddedStorageConfigurationBuilder builder = EmbeddedStorageConfiguration.Builder();
    EmbeddedStorageFoundation<?> foundation = builder
            .setStorageDirectory(dbPath)
            .setChannelCount(1)
            .setDataFileMaximumSize(ByteSize.New(2, ByteUnit.GB))
            .setHousekeepingTimeBudget(Duration.ofMillis(100))
            .setHousekeepingInterval(Duration.ofSeconds(1))
            .createEmbeddedStorageFoundation();
    EmbeddedStorageManager manager = foundation.createEmbeddedStorageManager().start();

    StorageRestServiceResolver.resolve(manager).start();

    TestStoreEntityRootLazy root = new TestStoreEntityRootLazy();
    root.obj1 = Lazy.Reference("abc");

    List<String> list = new ArrayList<>();
    for (int i = 0; i < 1_000_000; i++) {
      list.add(i + "");
    }
    root.obj2 = Lazy.Reference(new ArrayList<>(list));

    manager.setRoot(root);
    manager.storeRoot();
    //one.microstream.storage.types.StorageEntity$Default	64,003,968 B (28.1%)	1,000,062 (20%)

    TimeUnit.SECONDS.sleep(10);
    root.obj2.clear();
    System.gc();
    TimeUnit.SECONDS.sleep(10);
    System.out.println("clear & jvm gc.");
    //one.microstream.storage.types.StorageEntity$Default	64,003,968 B
    //StorageEntity$Default consuming memory unchange.
  }
}
```



```java
public class TestStoreEntityRootLazy
{
  Lazy<String> obj1;
  Lazy<Object> obj2;
}
```

ms version is : 07.00.00-MS-beta2

**Comment by hg-ms** [comment]
In your example the Lazy referenced List and its content can’t be deleted by the GC because the original list still exists. If you set that list to null all the strings can be delete after the clear() call:

```
list = null;
root.obj2.clear();
```
Additionally, the storage’s content is replaced with a new root at every run. I’m not sure if that is intentional.
Regrading the EntityCache, it will not shrink in all usecases to zero. It may keep empty entries. But the data behind the lazy should be unloaded.

Here is a example that should load and unload Lazy-References correctly:
```
public final class LazyReferencesDemo {

	public static class MyRoot {
		final Lazy<List<String>> data;

		public MyRoot(final Lazy<List<String>> data) {
			super();
			this.data = data;
		}
	}
	
	public static void main(final String[] args) {
						
		final Path workDir = Paths.get("./LazyReferencesDemo");
		
		//start and load/create storage
		final EmbeddedStorageManager storage = EmbeddedStorage.start(workDir);
					
		if(storage.root() == null) {
			//store some data if the storage  is new/empty
			final List<String> list = new ArrayList<>();
		    for (int i = 0; i < 1_000_000; i++) {
		      list.add(i + "A text of nonsens that has just the purpose to use up memory with its content."
		    		     + "A text of nonsens that has just the purpose to use up memory with its content.");
		    }
		    
		    //set a lazy referencing the new list as root and store it
		    storage.setRoot(new MyRoot(Lazy.Reference(list)));
		    storage.storeRoot();
		}
								
		//get the current root
		final MyRoot root = (MyRoot) storage.root();
		if(root.data.isLoaded()) {
			//this is only true if newly create above
			//unload the lazy
			root.data.clear();
		}
		
		// if existing storage has been loaded the lazy was skipped
		// load it now.
		root.data.get();
		System.out.println("lazy loaded: "+ root.data.isLoaded() + " elements: "+ root.data.get().size());
		root.data.clear();
		System.out.println("lazy loaded: "+ root.data.isLoaded());
				
		//shutdown everything
		storage.shutdown();
		LazyReferenceManager.get().stop();
	}
}
```

**Comment by 54446776** [comment]
Thanks for the answer. I understand how to use EntityCache correctly now.

After run your example code, I found there are DefaultObjectRegistry$Entry objects live after storage.shutdown().
one.microstream.persistence.internal.DefaultObjectRegistry$Entry	48,056,832 B (61.7%)	1,001,184 (68.3%)

Is a correct behaviours ?

**Comment by hg-ms** [comment]
You’re right. There are some flaws regarding the storage shutdown not releasing everything, like remainig entries in the ObjectRegistry...

If required, it is possible to clear the ObjectRegistry manually after the shutdown. 
```
storage.persistenceManager().objectRegistry().clearAll();
storage.persistenceManager().objectRegistry().consolidate();
```
If you do that, please ensure that you done reuse any already initialized Storage or Storage-Foundation if starting a storage again.

**Comment by 54446776** [comment]
Order take effect. Below code work for me.

```
storage.persistenceManager().objectRegistry().clearAll();
storage.persistenceManager().objectRegistry().consolidate();
storage.shutdown();
LazyReferenceManager.get().stop();
```

Thank you again.

**Comment by 54446776** [comment]
Memory is occupied by the StorageEntitiyCache is not a bug.
