### ISSUE TITLE
Moving code from version 6.1 to 7 generates unresolvable imports

### ISSUE THREAD

**Issue by HansITChange** [microstream-one/microstream#355]
* MicroStream Version: 6.1 migrating to 7
* JDK version: jdk 18
* OS: Windows
* Used frameworks: eclipse, maven

When moving to version 7.0, imports get invalid.

Import one.microstream.persistence.types: generates 'The import one cannot be resolved'

**Comment by rdebusscher** [comment]
Hi @HansITChange ,

Can you indicate the MicroStream artifacts that you use in your project and exact error message?

>'The import one cannot be resolved'

This seems to indicate that something went wrong when downloading the artifact.

Thx
Rudy

**Comment by HansITChange** [comment]
Hi Rudy,

This is what I have in my pom.xml:

```
                <dependency>
			<groupId>one.microstream</groupId>
			<artifactId>microstream-storage-embedded</artifactId>
			<version>07.00.00-MS-GA</version>
		</dependency>
		<dependency>
			<groupId>one.microstream</groupId>
			<artifactId>microstream-storage-embedded-configuration</artifactId>
			<version>07.00.00-MS-GA</version>
		</dependency>
```
and this is the error message I get:
![image](https://user-images.githubusercontent.com/30934446/166206026-25981a9d-971c-4179-9332-8eec3c4325cc.png)

The code still works under version 6.01 ...
Any ideas ?
Thanks,
Hans.

**Comment by hg-ms** [comment]
The import should work. 
Did you try to build your project using maven in the terminal (e.g. mvn clean package)?
You may also try to update the maven project in Eclipse (right-click the pom.xml -> maven -> update project)

**Comment by rdebusscher** [comment]
Hi Hans,

I cannot reproduce the problem.  I created a maven project with the same 2 artifacts and the Persister object is available.

The class is included in the transient dependency `one.microstream:microstream-persistence`.

This is the output of `dependency:tree` command
```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ testGH ---
[INFO] org.example:testGH:jar:1.0-SNAPSHOT
[INFO] +- one.microstream:microstream-storage-embedded:jar:07.00.00-MS-GA:compile
[INFO] |  \- one.microstream:microstream-storage:jar:07.00.00-MS-GA:compile
[INFO] |     +- one.microstream:microstream-afs-nio:jar:07.00.00-MS-GA:compile
[INFO] |     |  \- one.microstream:microstream-afs:jar:07.00.00-MS-GA:compile
[INFO] |     \- one.microstream:microstream-persistence-binary:jar:07.00.00-MS-GA:compile
[INFO] |        \- one.microstream:microstream-persistence:jar:07.00.00-MS-GA:compile
[INFO] \- one.microstream:microstream-storage-embedded-configuration:jar:07.00.00-MS-GA:compile
[INFO]    \- one.microstream:microstream-configuration:jar:07.00.00-MS-GA:compile
[INFO]       \- one.microstream:microstream-base:jar:07.00.00-MS-GA:compile
[INFO]          \- org.slf4j:slf4j-api:jar:1.7.32:compile
```

**Comment by HansITChange** [comment]
Hi,
I had (from previous versions) the following code in pom.xml :

```
<repository>
<id>microstream-releases</id>
<url>https://repo.microstream.one/repository/maven-public</url>
</repository>
```

After removing this and cleaning the project, it looks ok now.

Thanks for the help !
Hans.
