### ISSUE TITLE
"Optional Storage Manager Reference in Entities" doc incorrect

### ISSUE THREAD

**Issue by 54446776** [microstream-one/microstream#382]
## Environment Details
* MicroStream Version: 07.00.00-MS-GA
* JDK version: 17
* OS: Mac
* Used frameworks: none

## Describe the bug
https://docs.microstream.one/manual/storage/customizing/optional-storage-manager-reference-in-entities.html

class MyEntity
{
	String name ;
	int    value;
	transient EmbeddedStorageManager storage;
}
Using class type EmbeddedStorageManager always get null.
Change EmbeddedStorageManager to Persister get expected embeddedStorageManager instance as type Persister.

## Expected behavior
Correct doc content or support EmbeddedStorageManager reference type.

## Screenshots
<img width="400" alt="image" src="https://user-images.githubusercontent.com/19921794/177552696-d944488b-2368-419d-bfd6-c58410eec406.png">

<img width="400" alt="image" src="https://user-images.githubusercontent.com/19921794/177552998-2da6134c-efad-4972-8455-3d78e453c335.png">

**Comment by hg-ms** [comment]
Hello,
Many thanks for hint. This is indeed an error in the documentation. As you stated the field type has to be `one.microstream.persistence.types.Persister`.

TODO:
fix documentation
