### ISSUE TITLE
Automatically zip backup folder

### ISSUE THREAD

**Issue by JohannesRabauer** [microstream-one/microstream#400]
The backup functionality is great in MicroStream. It saves gigabytes of data within in seconds to the disk.

If i zip any backuped folder the gigabytes of data are shrunken to a few hundred megabytes. 
Since i run a backup daily the accumulated data is quite large. 

Now the proposal: Add an option to automatically zip the backed data. This way backed up data needs much less space.

**Comment by hg-ms** [comment]
Many thanks for your proposal.

If you use the one.microstream.storage.types.StorageConnection.issueFullBackup(ADirectory) API to create Backups a solution may be already available. You can utilize the Java ZipFileSystem (https://docs.oracle.com/javase/8/docs/technotes/guides/io/fsp/zipfilesystemprovider.html) to supply a target directory inside a zip file:

```
final Map<String, String> env = new HashMap<>();
env.put("create", "true");
final URI uriBkup = URI.create("jar:file:/backups/bkup.zip");
final FileSystem zipFsBkup = FileSystems.newFileSystem(uriBkup, env);
final NioFileSystem backupFileSystem = NioFileSystem.New(zipFsBkup);

storage.issueFullBackup(backupFileSystem.ensureDirectoryPath("backupDir"));

zipFsBkup.close();
```

Please note that we don’t support the ZipFileSystem officially. And the ZipFileSystem will not work as storage target or as target for the continuous backup.

best regards

**Comment by JohannesRabauer** [comment]
Thank you for your answer. We will try it out.
