### ISSUE TITLE
Provide a SBOM for MicroStream

### ISSUE THREAD

**Issue by rfichtner** [microstream-one/microstream#460]
## Is your feature request related to a problem? Please describe.
The creation of SBOMs is expected to be something that will be common practice, or sometimes even mandatory, when you deliver software. The US already has an "Executive Order on Improving the Nation’s Cybersecurity" with the SBOM requirement: 
 https://www.whitehouse.gov/briefing-room/presidential-actions/2021/05/12/executive-order-on-improving-the-nations-cybersecurity/ See Sec 4.E.vii

## Describe the solution you'd like
Create a SBOM for every build of MicroStream. Brian Vermeer has a good article about this topic: https://snyk.io/blog/create-sboms-java-maven-gradle/

## Describe alternatives you've considered
Having no SBOM ;) 

## Additional context
What is an SBOM? 
A software bill of materials, often abbreviated as SBOM, is a list of all software components used in an application. The SBOM is made up of third-party open-source libraries, vendor-provided packages, and first-party artifacts built by the organization. You can see it as the full list of ingredients for your applications. 

But be careful not to confuse an SBOM with Maven’s Bill Of Materials (BOM). 

An SBOM is something you create next to your application so that any user or client has a uniform way to find out what your application is using under the hood.

**Comment by rdebusscher** [comment]
GitHub provides this functionality by default now:  https://github.blog/2023-03-28-introducing-self-service-sboms/

**Comment by zdenek-jonas** [comment]
Implemented with PR:
https://github.com/microstream-one/microstream/pull/541
