### ISSUE TITLE
MS with Windows - Exception during start does not allowed to clean storage immediately after thrown.

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#48]
I have some following test. 
I create the storage with some file as root. Then I start storage again with root, what is not compatible and I expect an exception.
After this exception i will try to clean this directory. On linux works, on the Windows i received an Exception: 
`	Suppressed: java.nio.file.FileSystemException: C:\Users\ZDENEK~1\AppData\Local\Temp\junit1966308973519137683\channel_0\transactions_0.sft: Der Prozess kann nicht auf die Datei zugreifen, da sie von einem anderen Prozess verwendet wird.
`

So wee need to add some feature: 

I need some method: Something like `storage.waitToBeShutDown(Long timeout) ` which will block the problem until this storage has been correctly shutdown. 

Its not a bug, its feature request.

**Comment by tm-ms** [comment]
The problem with this is that currently, the active parts do not report back (notify) to the storage manager when they become completely inactive. So there can currently be no "wait until notified" mechanism that would be required to implement such a method.

The current solution is the method EmbeddedStorageManager#isActive which checks all active parts (channels, backup handler/thread, lockfile handler/thread) if they are still active. It only returns false if none of the parts is still active. This can be queried, maybe with a timed waiting, to wait until the storage is completely inactive after the shutdown order has been given.

Please check if such a solution would be sufficient for now.

**Comment by zdenek-jonas** [comment]
Getestet... works.... can be closed
