### ISSUE TITLE
Update CDI integration to use Jakarta EE after big bang.

### ISSUE THREAD

**Issue by otaviojava** [microstream-one/microstream#509]
Once we have more adoptions and vendors that use Jakarta EE, how about updating to CDI 3.0 or higher?

Does it make sense?

@rdebusscher 

Source code: https://github.com/microstream-one/microstream/tree/master/integrations/cdi

**Comment by rdebusscher** [comment]
PR for a jakarta namespace based integration is already under construction.  

Thx for opening the issue already.

**Comment by kmacedovarela** [comment]
Awesome! Would it be possible to share the link to the pr once its out?

**Comment by rdebusscher** [comment]
See https://github.com/microstream-one/microstream/pull/513

**Comment by fh-ms** [comment]
Done with #513
