### ISSUE TITLE
Annotated storage bean not found when using Spring Boot DevTools `RestartClassLoader`

### ISSUE THREAD

**Issue by magneticflux-** [microstream-one/microstream#517]
## Environment Details
* MicroStream Version: `08.00.00-MS-EA2`
* JDK version: `17`
* OS: Windows 11
* Used frameworks: Spring Boot

## Describe the bug
When using the "restart" feature of Spring Boot DevTools, the generated bean for my `@Storage` class is not autowired.

## To Reproduce
1. Generate a Spring Boot starter project including Spring Boot DevTools using [start.spring.io](https://start.spring.io/#!type=gradle-project-kotlin&language=kotlin&platformVersion=3.0.2&packaging=jar&jvmVersion=17&groupId=com.example&artifactId=demo&name=demo&description=Demo%20project%20for%20Spring%20Boot&packageName=com.example.demo&dependencies=devtools)
2. Add MicroStream Spring integration dependencies
3. Create a `@Storage` class and have it injected/autowired to something at startup
4. Launch the application ~with the added parameter `-Dspring.devtools.restart.trigger-file=.restartTriggerFile` (this is added by IntelliJ automatically if you set the run configuration's `On 'Update' action:` property to `Hot swap classes and update trigger file if failed`~ (this flag isn't needed, Spring always uses a `RestartClassLoader` when `spring-boot-devtools` is on the classpath)

## Expected behavior
The bean should be resolved properly

## Additional context
I suspect a class loading issue. I'm going to debug this on my own and I'll update with my findings or PR with a solution in an hour or two.

**Comment by zdenek-jonas** [comment]
https://github.com/microstream-one/microstream/tree/master/integrations/spring-boot#class-loader
Does this setting not help?

**Comment by magneticflux-** [comment]
No, it does not. The issue doesn't cause any `ClassCastExceptions`, just a mysterious missing bean.

I've got `microstream` cloned and building now, and I added an integration test for this failure. I think I've figured out a solution, so I'll make a PR with the new tests and fix in a few minutes if it works.

**Comment by zdenek-jonas** [comment]
Thank you for the PR. My colleague and I will look into it and let you know shortly. Good work.
