### ISSUE TITLE
wrong java command jar for rest app execution

### ISSUE THREAD

**Issue by guykatz** [microstream-one/microstream#548]
there is a documentation error in https://docs.microstream.one/manual/storage/rest-interface/client-gui.html
the java command stated in the java -jar is incorect.
the jar name is 'microstream-storage-restclient-app-07.01.00-MS-GA.jar'
the command in the docs page states 'storage.restclient.app-07.01.00-MS-GA.jar'
and so the command will yeild 'Error: Unable to access jarfile storage.restclient.app-07.01.00-MS-GA'
thanks

**Comment by hg-ms** [comment]
You’re right, thanks for the issue.
TODO: fix documentation.
