### ISSUE TITLE
non existing class reference in spark-java git docs

### ISSUE THREAD

**Issue by guykatz** [microstream-one/microstream#550]
in https://github.com/microstream-one/microstream/tree/master/storage/rest/service-sparkjava
the class StorageRestServiceDefault is referenced in all example but this class does not seem to exist in the API docs or in the microstream codebase (unless i missed something)
thanks

**Comment by hg-ms** [comment]
You’re right, thanks for the issue.
Should be StorageRestServiceSparkJava instead of StorageRestServiceDefault

TODO: fix documentation.
