### ISSUE TITLE
Support Example for Legacy Type Mapping

### ISSUE THREAD

**Issue by tm-ms** [microstream-one/microstream#62]
This stackoverflow question
https://stackoverflow.com/questions/59404226/microstream-lazyloading-relationship
requires an example that the actual problem here is the refactoring and an example on how to register a converter to get from a singular Author instance to a Lazy<List<Author>> instance.
Also some explanation, why that can't be done automatically (e.g. which List implementation should be chosen etc.) but substantial changes in the user's data model must be handled by the user himself.

**Comment by fh-ms** [comment]
There is an example online at https://github.com/microstream-one/examples/tree/master/customLegacyTypeHandler/src/main/java/one/microstream/sampler/customlegacytypehandler
