### ISSUE TITLE
pom.xml - testing dependencies definition

### ISSUE THREAD

**Issue by hrstoyanov** [microstream-one/microstream#628]
## Environment Details
* MicroStream Version: 8

## Describe the bug
The  Maven's  **pom.xml**  lists testing frameworks the wrong way. Such dependencies should  have "testing" scope, to be excluded from the final build:

```xml
       <dependency>
		<groupId>org.junit.jupiter</groupId>
		<artifactId>junit-jupiter-engine</artifactId>
		<version>5.8.2</version>
                <scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.junit.jupiter</groupId>
		<artifactId>junit-jupiter-params</artifactId>
		<version>5.8.2</version>
                <scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.mockito</groupId>
		<artifactId>mockito-core</artifactId>
		<version>4.3.1</version>
                <scope>test</scope>
	</dependency>
	<dependency>
		<groupId>org.mockito</groupId>
		<artifactId>mockito-junit-jupiter</artifactId>
		<version>4.3.1</version>
                <scope>test</scope>
	</dependency>
```

## Additional context
[What is the difference between <Scope>test</scope> and <Scope>Compile</Scope>?](https://stackoverflow.com/questions/58891154/what-is-the-difference-between-scopetest-scope-and-scopecompile-scope)

**Comment by zdenek-jonas** [comment]
Okay, this part just defines the versions. The usage is defined for each subproject with the appropriate scopes. Nothing less I'll add it there.
