### ISSUE TITLE
Building the MicroStreamTransactionFileConverte

### ISSUE THREAD

**Issue by hg-ms** [microstream-one/microstream#637]
Currently we have no build script provided for the MicroStreamTransactionFileConverter. 
It would be nice to have a maven profile to build it as a standalone tool. 
The related class is: 'one.microstream.storage.util.MainUtilTransactionFileConverter'

Many thanks

**Comment by zdenek-jonas** [comment]
```
mvn -P transaction-file-converter clean package
java -jar target/transaction-file-converter.jar ....
```
