### ISSUE TITLE
StorageDataFileEvaluator not working as expected

### ISSUE THREAD

**Issue by hg-ms** [microstream-one/microstream#65]
Executing an full file check with an custom StorageDataFileEvaluator does not show an effect.

1. Start an existing Storage without an individualy configured StorageDataFileEvaluator
2. create a new StorageDataFileEvaluator
3. issue an full file check using the new StorageDataFileEvaluator and a large time budget

```
final EmbeddedStorageManager storage = EmbeddedStorage.start(workingDir);
...
final StorageDataFileEvaluator dataFileEvaluator = Storage.DataFileEvaluator(1024, 1024*1024*1, 0.99, false);
storage.issueFileCheck(Long.MAX_VALUE, dataFileEvaluator);
```

debugging into the StorageDataFileEvaluator's needsDissolving method shows that the applied values are the storage default configuration values.

**Comment by hg-ms** [comment]
With the same code as in the first issue description but an lager storage the file check shows an different behavior: is seems to run endless.

in the first case the storage consisted out of one file with 2.7MB
in the second case (before the issueFileCheck call): 

Mode                LastWriteTime         Length Name
----                -------------         ------ ----
-a----       29.01.2020     12:54        8388600 channel_0_2.dat
-a----       29.01.2020     12:54        8388542 channel_0_3.dat
-a----       29.01.2020     12:54        8388600 channel_0_4.dat
-a----       29.01.2020     12:54        3970180 channel_0_5.dat
-a----       29.01.2020     12:54            362 transactions_0.sft

**Comment by hg-ms** [comment]
did some debugging:

In` one.microstream.storage.types.StorageFileManager.Default.transferOneChainToHeadFile(Default)`
the maximum file size is read from the StorageFileManagers StorageDataFileEvaluator and not from the one provided by the issueFileCheck(..) call.

**Comment by tm-ms** [comment]
As discussed with HG, it is actually questionable or even dangerous to allow a file check being called with a different file evaluator logic than the configured one. In the best case, it will have not effect (making it pointless) or mix up the files which the configured evaluator will clean up afterwards (again making it pointless with a pointless file storage taxation). In the worst case, it will create an infinite loop by causing a new file to be created and filled with a contradictory file size, causing another new file to be created and so on.

As a consequence, the solution was to remove the possibility to pass a custom file evaluator to file checks alltogether.

This fixes the described problem and implicitly concludes this issue.
