### ISSUE TITLE
why the microstream write performance is not good as DB? microsteam write cost is about 100ms+

### ISSUE THREAD

**Issue by useryq8** [microstream-one/microstream#688]
the original issue is https://github.com/microstream-one/bookstore-demo/issues/10,  the actual write cost is very bad.   
the batch mode can't be used for the actual case is that every user add one book and it needs to be stored into microstream to avoid data lost when app shutdown or machine shutdown accidentally. 

Do we have any best practice when using microstream,   for example StorageEntityCache.Default.setGarbageCollectionEnabled(false);  or set housekeeping to 24housr/15min, then call the issueGarbageCollection explicitly at scheduled time ?

such as, only using in reading scenario, not use in writing scenario(write all thing when app starts, not write in real-time when app is running).![image](https://github.com/microstream-one/microstream/assets/141137124/6612b37f-83d2-43df-aeb9-33f3ff8293a5)
 
arthas(https://github.com/alibaba/arthas) analysis log
![image](https://github.com/microstream-one/microstream/assets/141137124/e658a364-26b9-4d61-bdaa-d8b9a9e1dfac)
@fh-ms  @hg-ms

**Comment by fh-ms** [comment]
This is, I guess, a discussion of best practices for specific use cases.
