### ISSUE TITLE
PersistenceObjectRegistry#clear causes exceptions

### ISSUE THREAD

**Issue by tm-ms** [microstream-one/microstream#70]
FH reported that calling `PersistenceObjectRegistry#clear` for performance testing cache clearing puposes causes exceptions saying objectIds are already assigned.
This has to be investigated and fixed.

**Comment by tm-ms** [comment]
I tried a Lazy loading example (`MainTestLazyReferenceManagement`) with the lines
```
LazyReferenceManager.get().clear();
STORAGE.persistenceManager().objectRegistry().clear();
System.gc();
```
And could not reproduce the exception.
Neither directly during the PersistenceObjectRegistry#clear call, nor in the subsequent code that loads and registers the data again.

Please provide a code example that can reproduce the erroneous behavior.

**Comment by fh-ms** [comment]
It happens when you store after the registry has been cleared:

```java
final HashTable<String, Lazy<String>> root = HashTable.New();
root.put("foo", Lazy.Reference("bar"));

final EmbeddedStorageManager storage = EmbeddedStorage.start(root);
storage.storeRoot();

LazyReferenceManager.get().clear();
storage.persistenceManager().objectRegistry().clear();
System.gc();

root.put("wait", Lazy.Reference("what"));
storage.storeRoot(); // -> Exception: ObjectId already set: 1000000000000000033
```

**Comment by tm-ms** [comment]
I tested the example above and found a two-part reason for the behavior.

1.)
The direct cause is a bug in the example code.
The LazyReferenceManager gets set and started in EmbeddedStorage.start(), but the first lazy reference is created before that.
Thus, it is never registered at the LRM, thus never gets cleared.

There are two ways to fix this:

Either put the "foo" entry between .start() and .storeRoot()
or set a proper LRM explicitely before creating the first lazy reference.

2.)
That the second fixing alternative is required in the first place made me think:
If a lazy reference is never properly usable before a proper LRM is set, this has to be enforced so that the developer won't run into the trap described above.
Either by checking and throwing an exception or, preferably, by having a proper LRM from the beginning.

I am still against creating an active thread out of the blue, but so far, I never realized:
An LRM works even without its thread. Hence, a proper LRM instance could be set from the beginning, so it is there for all lazy references to register and even for havnig its cleanup logic called manually.
Then, all the storage starting has to do is to ensure there is a running LRM thread for automatic checking.

I will change that and test with the provided example.

**Comment by tm-ms** [comment]
I removed the LRM Dummy implementation and instead set a proper LRM from the beginning.
This fixes the described problem. See `MainTestAlwaysProperLazyManaging`.

To avoid inconsistencies between an old an a newly set LRM, I added a registerAll(LRM) method that gets called in the static set method.

This change should conclude this issue.

**Comment by tm-ms** [comment]
This change broke the automatic shutdown from microstream-one/microstream-public#60:
The initially created and set LRM cannot have a reference to the not yet existing storage manager instance to synch its shutdown to it. When the LRM starts, there is currently no way to set the LRM's final field.

The solution is to make the field mutable with a setter. Of course with the necessary synchronization and checks (no other parent reference exists, yet, etc.)

**Comment by tm-ms** [comment]
This has been fixed, but a simple setter did not suffice.
Since the LRM is a singleton per JVM process (since it takes responsibility for the whole heap one way or another, so splitting the task into multiple LRMs could be fatal...), there can potentially or WILL eventually be multiple storage managers that have to register at the LRM.

This means there has to be a linked-list-like chain of "parent" LRMs. Of course weakly referenced. With automatic chain consolidation. Special case handling if the chain is empty.
Also: again, when an LRM replaces the existing one, there needed to be a method to transfer the chain to the new LRM. Of course thread-safe, ...

This added up to quite some implementation work, but it is now completed and tested.
