### ISSUE TITLE
REST-Service UI-Layer

### ISSUE THREAD

**Issue by fh-ms** [microstream-one/microstream#74]
Suitable for the storage REST service (#35), we will provide a client, consisting of two parts:

- Java wrapper for REST calls
- Vaadin UI layer with a component collection and a standalone application

**Comment by fh-ms** [comment]
Info for Testing:
- Branch is feature/priv224_REST-Service_UI-Layer
- Start test server class: MSWorkInProgress / one.microstream.storage.restservice.MainTestStorageRestServer
- Start client app: MSStorageRestClientApp / one.microstream.storage.restclient.app.Application
- Open http://localhost:8080

**Comment by zdenek-jonas** [comment]
Bug found: https://github.com/microstream-one/microstream-private/issues/249

**Comment by zdenek-jonas** [comment]
There are several bugs found:
https://github.com/microstream-one/microstream-private/issues/253
https://github.com/microstream-one/microstream-private/issues/254
https://github.com/microstream-one/microstream-private/issues/255
https://github.com/microstream-one/microstream-private/issues/256
https://github.com/microstream-one/microstream-private/issues/257
https://github.com/microstream-one/microstream-private/issues/258

and two enhancement created:
https://github.com/microstream-one/microstream-private/issues/251
https://github.com/microstream-one/microstream-private/issues/252

**Comment by zdenek-jonas** [comment]
All binary handlers are tested. I'll add tests for binary handlers for issue microstream-one/microstream-private#117 and these will tested too.
