### ISSUE TITLE
INI parser beim Configuration loading ignores "\"

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#75]
INI parser beim Configuration loading ignores "\\"

Config file:
```
baseDirectory = C:\Users\ZDENEK~1\AppData\Local\Temp\junit1562739913904277362
```
is changed into:
```
UsersZDENEK~1AppDataLocalTempjunit1562739913904277362
```
in actual process work directory.

Windows path format should be accepted as correct path entry.

**Comment by fh-ms** [comment]
Fix commited in master

**Comment by zdenek-jonas** [comment]
Retest ok. I close this issue.
