### ISSUE TITLE
Maybe replace Class.forName?

### ISSUE THREAD

**Issue by tm-ms** [microstream-one/microstream#78]
Research from HG for ticket J20E resulted in some statement that Class.forName should not be used as it can lead to problems like the one described in the ticket. Classes being loaded by different class loaders etc.

A quick googling to the topic indeed revealed some questions:
https://stackoverflow.com/questions/8100376/class-forname-vs-classloader-loadclass-which-to-use-for-dynamic-loading
https://stackoverflow.com/questions/4285855/difference-between-loading-a-class-using-classloader-and-class-forname

Maybe some or even many class loader problems could be solved by using the other approach.
Maybe even an enhancement using a customizable "ClassLoaderProvider".
(_"There is no problem in computer science that cannot be solved by one more level of indirection"_ ... :-D)

**Comment by tm-ms** [comment]
I replaced Class#forName default behavior in XReflect#resolveType by calling `Class.forName(typeName, true, classLoader)`, with the classLoader instance being provided by a ClassLoaderProvider instance which returns ClassLoader.getSystemClassLoader() by default.
The ClassLoaderProvider instance to be used can be customized in the PersistenceFoundation.

The old behavior is kept in the new method `XReflect#resolveTypeForName`. However itis currently not used and there is currently no reason in sight why one should.

**Comment by tm-ms** [comment]
As microstream-one/microstream-private#238 shows, the underlying asumption to the changed default behavior was wrong.
A new default behavior concept must be conceived and implemented.

**Comment by tm-ms** [comment]
Breathtakingly trivial idea:
The ClassLoader instance to be used for resolving types later on must be the same that was used to initialize all the type handling stuff, i.e. the same that initialized the foundation in the first place.
This guarantees in an almost painfully simple way that both are the same.
\* cough cough *

That ClassLoader is trivially queried by calling this.getClass().getClassLoader() in the foundation instance when ensuring a ClassLoaderProvider.

**Comment by tm-ms** [comment]
@hg-ms please test with the already setup customer project.

**Comment by hg-ms** [comment]
Tested current head 935ab52f from 9. March 2020 
in tmc_kis customer project:

The project now start without exceptions
one.microstream.persistence.exceptions.PersistenceExceptionTypeConsistency is not thrown

->  Test successful, bug seems to be solved
