### ISSUE TITLE
Collections update, range comparison

### ISSUE THREAD

**Issue by fh-ms** [microstream-one/microstream#84]
For the JCache implementation it would be good to have following methods of `ChainStorage` available in `HashTable` and `EqHashTable`. 

```java
public E rngMin(long offset, long length, Comparator<? super E> comparator);

public E rngMax(long offset, long length, Comparator<? super E> comparator);
```

This would be a major performance gain for the eviction algorithm.

**Comment by tm-ms** [comment]
The rng~ methods in the X-Collections were a "premature optimization" overkill of early design days.
The same functionality can be achieved by using a custom Consumer function, for example an Aggregator.
I wrote and committed the class `MainTestRangedMinMax` that does exactely the desired logic without having to implement it in a hardcoded way.
This generic way might be a few % slower than hardcoding the logic, but it is infinitely more flexible and the few % speed should actually never matter.
If an application has such extreme performence demands for such a logic, it should best be implemented in a completely customized way and be even faster than with using the general-purpose collection.

Regarding the X-Collections source code, it's actually the opposite: I should cleanup the internal ChainStorage~ implementations and remove all those internal legacy rng~ method stubs that are have never been implemented.

**Comment by tm-ms** [comment]
I removed all rng~, keyRng~ and valuesRng~ methods from the two "chain storage" classes that back the single- and dual-key hashing collections.

Since FH said the solution provided above is sufficient, this issue (and at last the topic of the overkill "rng~" methods) can be closed.
