### ISSUE TITLE
Cache must implement org.hibernate.cache.spi.RegionFactory for Spring + Hibernate integration

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#88]
Cache must implement org.hibernate.cache.spi.RegionFactory for Spring + Hibernate integration

Quele:
https://www.baeldung.com/hibernate-second-level-cache

Class is in  org.hibernate:hibernate-core

**Comment by fh-ms** [comment]
Implemented Hibernate Cache Region Factory.

Available in branch:
`feature/priv196_jsr107_jcache_implementation`

Dependency:
```xml
<dependency>
	<groupId>one.microstream</groupId>
	<artifactId>cache.hibernate</artifactId>
	<version>02.03.00-MS-GA-SNAPSHOT</version>
</dependency>
```

Region Factory:
`one.microstream.cache.hibernate.CacheRegionFactory`

Spring Config
```
spring.jpa.properties.hibernate.cache.region.factory_class=one.microstream.cache.hibernate.CacheRegionFactory
spring.jpa.properties.hibernate.cache.microstream.missing_cache_strategy=create
```

Further configuration:
hibernate.cache.microstream.missing_cache_strategy=[fail|create-warn|create]
hibernate.cache.microstream.configurationResourceName=cache config file URL
hibernate.cache.microstream.cache_lock_timeout=timeout in ms

**Comment by zdenek-jonas** [comment]
Works...
