### ISSUE TITLE
Idea - persistence cache with Microstream

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#89]
Motivation:
One needs sometimes services, which cache a lot of data. During restart of this services is in memory cache invalided and the whole data set has to be loaded from DB again. 
This idea is to use this cache als persistence cache. So the app can started with the cached data again to avoid this peak on the start. 

This should be already possible to do. We should just provide a spring configuration for this feature. 
Some possible solution: 
a)
In application properties something like this
```
one.microstream.cache.persistence=true
one.microstream.cache.directory=/opt/app/data
```

b)
Just add into application.properties path to Microstream config
```
one.microstream.config.location=/opt/app/cache.config
```
Or better, just add autoscan and when file e.g. 'microstream.ini', automatically load it.

**Comment by fh-ms** [comment]
Is already possible, see gitbook draft 3.0: Cache -> Configuration -> Storage
https://app.gitbook.com/@microstream/s/manual/~/drafts/-M3FoN5DiegfkCHSBed_/cache/configuration/storage/@drafts

**Comment by zdenek-jonas** [comment]
Current implementation is much better than the first idea was. So i am satisfied with current implementation and i close this issue.
