### ISSUE TITLE
Communication Host-Only Type Dictionary update

### ISSUE THREAD

**Issue by hg-ms** [microstream-one/microstream#90]
Based upon microstream-one/microstream-private#134 that suggests:

> 2.) Host-Only
The host will dynamically extend its type dictionary as needed and notify the client(s) on every new type for a corresponding type synchronization.
The client is only allowed to use types defined in the type dictionary.

This requires a second communication implementation:

- the host must be enabled to extend it's type dictionary 
- the host must notify the client on the new type
- the client must be enabled to update it's typ dictionary in case the host sends a new type entry

**Comment by hg-ms** [comment]
the latest implementation is included in microstream-one/microstream-private#306

**Comment by zdenek-jonas** [comment]
ok
