### ISSUE TITLE
REST-Service UI-Layer - StringBuffer is content shows as a 'long' with String value

### ISSUE THREAD

**Issue by zdenek-jonas** [microstream-one/microstream#98]
REST-Service UI-Layer - StringBuffer and StringBuilder shows content as a 'long' with String value

```
    static class StringBufferData  {
        StringBuffer value = new StringBuffer();

        public void fillSampleData() {
            value = new StringBuffer().append("Some Text").append("SecondText")
                    .append("A, Á, B, C, Č, D, Ď, E, É, Ě, F, G, H, Ch, I, Í, J, K, L, M, N, Ň, O, Ó, P, Q, R, Ř, S, Š, T, Ť, U, Ú, Ů, V, W, X, Y, Ý, Z, Ž.")
                    .append("a, á, b, c, č, d, ď, e, é, ě, f, g, h, ch, i, í, j, k, l, m, n, ň, o, ó, p, q, r, ř, s, š, t, ť, u, ú, ů, v, w, x, y, ý, z, ž.");
            ;
        }
    }
```
is shown as 
![image](https://user-images.githubusercontent.com/17253582/78018700-a91b3f80-734e-11ea-9c17-8798c75886d8.png)

**Comment by hg-ms** [comment]
added "simplified" flag to ViewerObjectDescription that indicates that the returned ViewerObjectDescription has only the value as it is returned from the microstream native type handler for the corresponding type

**Comment by zdenek-jonas** [comment]
ok
